/*
 * BrightTable // Copyright (C) 2026 Rob Brown
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//! The bundled lensfun lens/camera list (`resources/lensfun-catalog.json`,
//! regenerated by `scripts/gen-lens-catalog.mjs` from a lensfun checkout -
//! CC-BY-SA 3.0). Lens entries are what the Change Lens picker offers with
//! their exact lensfun names; camera entries supply crop factors for
//! `FocalLengthIn35mmFormat`.

use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

const CATALOG_JSON: &str = include_str!("../resources/lensfun-catalog.json");

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogSource {
    pub repo: String,
    pub commit: Option<String>,
    pub date: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogLens {
    pub maker: String,
    pub model: String,
    pub display_name: Option<String>,
    pub mounts: Vec<String>,
    pub crop: Option<f32>,
    pub focal_min: Option<f32>,
    pub focal_max: Option<f32>,
    pub aperture_max: Option<f32>,
    pub aperture_max_tele: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogCamera {
    pub maker: String,
    pub model: String,
    pub crop: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LensCatalog {
    pub source: CatalogSource,
    pub license: String,
    pub lenses: Vec<CatalogLens>,
    pub cameras: Vec<CatalogCamera>,
}

pub fn catalog() -> &'static LensCatalog {
    static CATALOG: OnceLock<LensCatalog> = OnceLock::new();
    CATALOG.get_or_init(|| serde_json::from_str(CATALOG_JSON).expect("bundled lensfun-catalog.json is valid"))
}

/// Lowercased, with runs of whitespace collapsed - lensfun's own camera
/// matching is case-insensitive (`LEICA M10-R` in EXIF vs `Leica M10-R`).
fn normalize(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ").to_lowercase()
}

/// The camera's crop factor, matching EXIF make/model against lensfun's
/// camera list. Makers differ in spelling between EXIF and lensfun
/// ("NIKON CORPORATION" vs "Nikon Corporation", "samsung"), so the maker
/// only has to share its first word.
pub fn camera_crop_factor(make: &str, model: &str) -> Option<f32> {
    let model_n = normalize(model);
    let make_word = normalize(make).split(' ').next().unwrap_or("").to_string();
    if model_n.is_empty() {
        return None;
    }
    catalog()
        .cameras
        .iter()
        .find(|c| normalize(&c.model) == model_n && (make_word.is_empty() || normalize(&c.maker).starts_with(&make_word)))
        .map(|c| c.crop)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_parses_and_has_lenses() {
        let c = catalog();
        assert!(c.lenses.len() > 1000);
        assert!(c.cameras.len() > 500);
        let summicron = c.lenses.iter().find(|l| l.model == "Summicron-M 1:2/50").expect("Summicron-M 1:2/50 in lensfun");
        assert_eq!(summicron.maker, "Leica Camera AG");
        assert_eq!(summicron.focal_min, Some(50.0));
        assert_eq!(summicron.aperture_max, Some(2.0));
    }

    #[test]
    fn crop_factor_matches_exif_spelling_case_insensitively() {
        assert_eq!(camera_crop_factor("Leica Camera AG", "LEICA M10-R"), Some(1.0));
        assert_eq!(camera_crop_factor("", ""), None);
        assert_eq!(camera_crop_factor("Nobody", "No Such Camera 9000"), None);
    }
}
